name: JoinRestrictor
main: com.zenologia.joinrestrictor.JoinRestrictor
version: 1.0
api-version: 1.17
author: Zenologia
commands:
  joinrestrictor:
    description: Reload the JoinRestrictor config.
    usage: /joinrestrictor reload
    permission: joinrestrictor.reload
